    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACTpYcnhCIjUefvM7MEEY5-a/panphlan_aactinomycetemcomitans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADxInu42C9LKM1jvEycAvsOa/panphlan_aaphrophilus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD5Wl2cuhnhk6cTlbMMQcCja/panphlan_abereziniae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADMNGCvxBua0ZE16_8fVjEqa/panphlan_abirgiae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABtNANAVIGvxmWUpasH8Zxea/panphlan_acardiffensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAPXKSO2ol3lAQeEQ02ZKYqa/panphlan_acolihominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB7KIq70EF7-fJB00V3vuT5a/panphlan_adefectiva16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADanuZh3v65vnPGl3Zegn9Ha/panphlan_aebreus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADweyOqkzgdYDbFeVf73W0Fa/panphlan_aequolifaciens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAzFhvt9RYzwnaS1Lqi_ayPa/panphlan_afinegoldii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACdq1uI1-w9L6yKf8f46u5Wa/panphlan_afumigatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAZnIaNvD0Y71aXAscyRZNoa/panphlan_ageorgiae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAsbjO7gTtd1qgHgYjLuGXsa/panphlan_agraevenitzii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACPEKH2LtI4iRBb3ay1_L_Na/panphlan_ahadrus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAXhxp07Iws8_F2XiPk6bewa/panphlan_ahydrogenalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABWrthK-Mdb4UkNcZ1jKKhWa/panphlan_aindicus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABOmG52MDmmaAXdMicRcQUHa/panphlan_aindistinctus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD1_blRvp9rqw77rTa9AGmCa/panphlan_aintestini16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABRYPQpIWHt-FWTkTkQN1eya/panphlan_ajohnsonii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADazcAENPLGb3JkNa0uZj8ia/panphlan_ajunii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACcIJCukaYvhRIjqX0kSDLja/panphlan_alactolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADb4fwzplIPnqpLkoKKuBkNa/panphlan_alwoffii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB5LGqqYRZxC0XWIBqZlUW2a/panphlan_amassiliensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADi39QNLrO7_ahq8yXIuDtwa/panphlan_amuciniphila16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA8u2mIr8GUYsR6W0Qv_8CYa/panphlan_anaeslundii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABs8RoBGyAt_RgGQMHDtZHZa/panphlan_aodontolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACtkG_ycun8S-HtE7UdGDnXa/panphlan_aomnicolens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB-jvihIu-r_wCm_tHYzeqVa/panphlan_aonderdonkii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAio-IOEBtMWo93pWLC3zc_a/panphlan_aotitis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAY0DjIYOgoYFqce21KSmbYa/panphlan_aparvulum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACzomBqGfHpzrs0BIwOZSC4a/panphlan_aprevotii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADM3L9Egrv8F0CYRjqDT3mKa/panphlan_aputredinis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACWIUB72BIX7-RfhH67Ya6ya/panphlan_aradioresistens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB2wr0C_kp5WLc343FMj0XDa/panphlan_asenegalensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACtSS8XRrsCt5C5RoDtjZVza/panphlan_ashahii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC6TlJ5c88NqnaC32EZmo8ua/panphlan_astercorihominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABf80O-lE2LbaQ4FXGLG5fIa/panphlan_atannerae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAR5sFohWaslxhkBQ5UGVLFa/panphlan_atimonensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACFkxfRwdWdPeg7H38ZixZXa/panphlan_atumefaciens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACrhDDKpyHphZK001OzInp3a/panphlan_aurogenitalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAMXwJmik1tP5Hareq2M15Da/panphlan_aursingii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACfJDRWmyNUxCgRvLiWgdWGa/panphlan_avaginae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAnMZZnhsPWYCEqx3olEoTEa/panphlan_avaginalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC_APqf76_tunPgqX2u0Bjea/panphlan_avenetianus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACs2rl4cnjmbMXjXBr2H109a/panphlan_aviridans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADHOo4T0Vv0Af3nBqQFa9E0a/panphlan_aviscosus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAC86yssgj2FLYtqvwUUG4Na/panphlan_badolescentis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD272_R3nC5c-7a5i2gvgL5a/panphlan_bangulatum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAxJJARudc0KY5xxuzN6ASJa/panphlan_banimalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAxTZTBHU9YrGek9cYuoKona/panphlan_baphidicola16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACAJ_4CrnphNxZSCy4ag02Ua/panphlan_bbifidum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACdYSfZ_aWEil0XSoQ_wuuYa/panphlan_bbreve16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC5hpLCubiEJTwCSN60-9pea/panphlan_bcaccae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABqtdSKasLm4g1X1jpMJ2dta/panphlan_bcasei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACIj-ni_zqa7xwL6Z7wH09Da/panphlan_bcatenulatum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAxWpa4UOtja3CEKuDMG96ha/panphlan_bcellulosilyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC4DI-nWVnEumaS91CpBMh4a/panphlan_bcenocepacia16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABV4Cdzo7a-gGPTXXxy2xsZa/panphlan_bclarus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADX0MR1pnP5XAULFr8wQIFSa/panphlan_bcoprocola16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB5ljuOZKkUSO5S8JYiYjvra/panphlan_bcoprophilus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC457Stb1NANL8MIIJhyrpra/panphlan_bcrossotus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADRYKffQX6qyn4CcrWCb8Uua/panphlan_bdentium16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC7Y_WgOa4srRHyqaQZEWRxa/panphlan_bdiminuta16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACC2R217ADUi6bmfdMvRdLWa/panphlan_bdorei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC7OPYicVkGNMcs50EH63Mka/panphlan_beggerthii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADslF87G6VLQDGVoG_QC1bva/panphlan_bextructa16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACC35kcmrVAiuIFk3_UsE9ka/panphlan_bfaecis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADivHerJ14k_2GdvtPz1qxPa/panphlan_bfinegoldii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADx5u1H6-PaGwA_uV57gICZa/panphlan_bfluxus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADiFeHFPPbvQEMixHZIvFUMa/panphlan_bfragilis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAjdcmtI39skq-Fq2nv4MJ7a/panphlan_bgallinarum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAiIoDVZDIK6tnlFTEozxVta/panphlan_bhansenii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADpY5LPqt3d0pIoexUD52fya/panphlan_bhydrogenotrophica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB2EIxwcA_1l3NAaeLpFGVia/panphlan_bintestinalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAF2z_D7uCqO9EV2StRSWDKa/panphlan_bintestinihominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABaBRJMTf0LldVbYe5mDXhDa/panphlan_blongum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABmAspoetujpDX9Dku9YsYMa/panphlan_bmassiliensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACDhyO1h2JjuF6uWYHqZz8za/panphlan_bmcbrellneri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABG-eKhKAzw2HNGNSE6zs5ia/panphlan_bnordii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADU71r2MaHyXzukk32w0IrNa/panphlan_boleiciplenus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB7w_LfKTMLjswd4TweQIwVa/panphlan_bovatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA1ursajOO-Ko10QEw9-02va/panphlan_bpectinophilus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABg7FypEKq_B-nHrhgIZzvVa/panphlan_bplebeius16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABad0CO68ila37xVyDkz0M5a/panphlan_bproducta16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABt-lCp7wHbpUijAvI6Jgnpa/panphlan_bpseudocatenulatum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADYeE5M55U68WJrU-zZeEsma/panphlan_bpullicaecorum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC6LeAaQcusiQUeqUlZWSAHa/panphlan_bsalyersiae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAxdwOm-sd_aDuT4BJH1411a/panphlan_bstercoris16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADZgjK2uLNsLLRe_EM4ikuca/panphlan_bsynergistica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADu4dABWk5MZlzOOhQnb7iJa/panphlan_bthetaiotaomicron16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADpWgV1Yqo09tWfg_bJ6xJka/panphlan_buniformis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACJK3x6uZQtpBoU7eTEoelra/panphlan_bvulgatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC0xnlG2WMAZVLA2u_0Yndqa/panphlan_bwadsworthia16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABB6qmtNQPQE29kAFrVk9Mxa/panphlan_bxylanisolvens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABR6PANq6E5l9i1cmecT9ZFa/panphlan_bzoohelcum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD2dOy-eha-0sz7d-2xMt3Ea/panphlan_caccolens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADfhhQcTfNXvTw-RmJOulX0a/panphlan_caerofaciens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACFfXrVku8pS2p9gzvMUgI3a/panphlan_calbicans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA94Y_qgDIbbg-9qOsYvnCta/panphlan_camycolatum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAmwAXoW1nf0Ntc_d_dtuoea/panphlan_casparagiforme16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADp-5H5WJFhza6AEzP2wBjFa/panphlan_caurimucosum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAzpKSFOZ9F2jy_N7_nebDla/panphlan_cbartlettii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACcgFHuzk6PPV88dy9xg2Gla/panphlan_cbolteae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACFFpuGyma5HVg9PCUaxPQMa/panphlan_cbovis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACdhCASrYontrEuK2P28xvda/panphlan_ccatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADzy9faBKX2C3cYZidDrXxJa/panphlan_ccelatum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADsO-bppafhfC-KdLK7JH-1a/panphlan_ccitroniae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACSCjtQ90EOImslNKDxP_5ua/panphlan_cclostridioforme16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADGe1eQCGlsUQJ7K7D_6HBaa/panphlan_ccomes16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAEa9DqDNZA-UnSgK2pJFsCa/panphlan_cconcisus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC0tPrAZdyPk7Nn6Capvviva/panphlan_ccurvus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAXb1NSetMSAbv6BTCczaNGa/panphlan_cdubliniensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABVSRTmJ0mBnguthvtXzE8fa/panphlan_cdurum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADyGaqhw_jJO9sFjZ5raAA5a/panphlan_ceutactus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAZ6U8gOOFLp9psjECD8FgOa/panphlan_cfreundii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAYI43GrwRP8n4-n69FWAosa/panphlan_cglabrata16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADOM4Ng0HRfrjaWTCTOH83Ja/panphlan_cgracilis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACR1fhWvIT5iAreRJCpOehMa/panphlan_cgranulosa16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAbCW6ozNnROhqnGXmzqOR6a/panphlan_chathewayi16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABabkhrKf8DWRpWwbri3JOQa/panphlan_chiranonis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC5FAWcLZSwbueoR5CkTc63a/panphlan_chylemonae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAM4JEZIexMgPVh4pRYH2kLa/panphlan_cinnocuum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABQrXmavhmVZ6ukKDgl_HpZa/panphlan_cjeikeium16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACO3HfEH6Ryy_NVhDHFumLwa/panphlan_ckroppenstedtii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAFPma2rwdGWsvj4v9Mgj7_a/panphlan_cleptum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABB0PvAj2euhhfH9EZ_SBvCa/panphlan_clipophiloflavum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACGwrssLii4jWf3_vJ6CZZga/panphlan_cmaltaromaticum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAfTQFvq1HObNm_oGlfSo64a/panphlan_cmatruchotii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAjrqxOAPKC82JpNZAaAU0fa/panphlan_cmethylpentosum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABEChyfjYJG6VchxPGVeGpha/panphlan_cmitsuokai16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADVwi6ierHJuI_InBH5f3d3a/panphlan_cmorbi16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADCkS9Kw87ILeSitUZv3ZHba/panphlan_cnexile16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC7i6vstNUJ-xsGRhond3Yna/panphlan_cochracea16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACWAjIzPDlnmBBX4_gV55Rfa/panphlan_cperfringens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABAbMiN_PeIHm5kcqHiTjiTa/panphlan_cperiodontii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAcxG2ZuVwfKlXGC8HoKikBa/panphlan_cpropinquum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACMvYKVL8S9Lm6Pu3mjmpJca/panphlan_cpseudodiphtheriticum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABVjz9CffUJa1yHTSeJMXyda/panphlan_cscindens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADXZJCpNwo8G0qNSij7bjzna/panphlan_cshowae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACJ8IiC_DtuCIVaf3x94mcta/panphlan_cspiroforme16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC_Pvvn2IjRlGxmqPU-e0JPa/panphlan_csputigena16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADmJm1jazQSQXTGYuxT8yv9a/panphlan_cstercoris16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD95DrIjwem0pASnjbx9Egka/panphlan_cstriatum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAATbcFGbq0sXhcGGGGX8EQwa/panphlan_csymbiosum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACcdLMc4vYu-jvO5iRPMUP1a/panphlan_ctanakaei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABTQmMEkhQhoxo70AEoQewTa/panphlan_ctestosteroni16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA290mD3vurylcNe1M3_vsza/panphlan_ctimonense16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAmy_Tc25gMGTWom24UGqHTa/panphlan_ctropicalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAlJ6mPWyAffSHHv5tgjTpxa/panphlan_ctuberculostearicum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA_-otZNBLsd8oFEo9xF6HQa/panphlan_curealyticum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACy8_VtteiE1oxc55WW2DbDa/panphlan_cureolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABOSSpvznaUaUrZ3HCvGqdfa/panphlan_cvalvarum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAchtNv4oqClK0ebFxHjH3Ta/panphlan_cvariabile16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACYRn_fHJuEKiSmtz_EuO5Ba/panphlan_ddesulfuricans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAR7pvEC0n5yrwwCxCf6fB-a/panphlan_dformicigenerans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACwNM0BlQQwkFCPsJ8SC8cIa/panphlan_dinvisus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABDLbQHJX3yhm2LYG_C6lU4a/panphlan_dlongicatena16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACIZrqHoCev6g38Qf-0gGPia/panphlan_dmicraerophilus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADQUcAPgkPQzFturZJumUNna/panphlan_dpigrum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAoJM_XTOA6Chu131oLURkOa/panphlan_dradiodurans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADPuzdsTwcYBo4A9kzhgmnHa/panphlan_dsuccinatiphilus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACqwUkfuzpFpNL5n4rS9GBga/panphlan_eaerogenes16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAATTF9ScW6J0K8BGs9X_cxGa/panphlan_eaerosaccus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABK1zGjsV384FPJeXSoPsuna/panphlan_ebrachy16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACIDUb9SguxKTLjRENtSlYaa/panphlan_ecatenaformis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC4mIlAvNKKtC1x-5tIe93Aa/panphlan_ecoli16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAadx5FdWm0IpgPpTKqpjeDa/panphlan_ecorrodens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAlEqNefqj84xp2CIKriK2da/panphlan_edispar16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACVqryZMuDO8PMpqktsGSGUa/panphlan_edolichum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAWPF8YAj7J5jendrZkshdda/panphlan_eeligens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABDErk3J1BraFwlHCGZyZUXa/panphlan_efaecium16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABGbmfMRZfjv0MNLrL6Zd8Da/panphlan_egallinarum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADMwGryhkgWFI-XpIDgz62Ra/panphlan_ehallii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABw_bt9dYarKZteRdXYeLrOa/panphlan_einfirmum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAVG9Uh4vkEuyDypL0mkSj5a/panphlan_elenta16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACYouMJatCV1dmIARevrzi1a/panphlan_elimosum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACNOhG-9IuGRjZaI4f5dXKJa/panphlan_erectale16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAgqF9RUDOJljlr49AAzYUoa/panphlan_esiraeum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABBxVnLZ23_G4_XjOYox2zpa/panphlan_ffastidiosum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAApLEAwHM_SYsvI7T_ow0Ata/panphlan_fgonidiaformans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADdUtnh0eUMh4PiGamDcgkla/panphlan_fhominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACx4_2qV5VeTeVMIpTR9ctEa/panphlan_fignava16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADXfH1yaimGuoRDYJ450-bIa/panphlan_flanguida16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACpSrRlO55Amz0kce59chuFa/panphlan_fmagna16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADllVjahakxFCs_bJafhM9sa/panphlan_fmortiferum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABLfO2hQ5DGLIFkEzaYDJRsa/panphlan_fnecrophorum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADJgniLFv6uk0v8eGzLqp0na/panphlan_fnucleatum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB_7SDqz3K2yloX3MgMvNNAa/panphlan_fperiodonticum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACuJE_eR6IVvayWXxVU79vMa/panphlan_fplautii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACGekyBtm0hcYLOb9-w6b4_a/panphlan_fprausnitzii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAt2obojmw7lbSyooeJNEdja/panphlan_fulcerans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAidBs1fBEQGOWCTB3P_MYZa/panphlan_gadiacens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAr4bTcPaIg25tpl1Q-kGFIa/panphlan_gbergeri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAr3rKXilcX49rC_VB8TNG7a/panphlan_gelegans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACXlpzn__FUqxIcfrhO8fQxa/panphlan_ghaemolysans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACtqfklrnXAhFfa2VA7v9csa/panphlan_gmorbillorum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABMd1kq4dU24SJy3pULqm9va/panphlan_gpamelaeae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADnQ1sxBRnHu3PnG_bPb82oa/panphlan_gsanguinis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACbQnmb8XYH95hq-MttNFuXa/panphlan_gterrae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABlV45MFRrpDG5E_XEcJ88ta/panphlan_gvaginalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAKuijX4J14mMOIDUA3DuL0a/panphlan_hhaemolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABV3Q0wK3pGYcVxQOMYXW_Ca/panphlan_hinfluenzae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAFiHRAiYUOgfPrvsXv8pCZa/panphlan_hparahaemolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD4jx-7tv4iSL7E6io1ySVCa/panphlan_hparainfluenzae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC27V8cc32pmuNQsO0ZbHfGa/panphlan_hparaphrohaemolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABtDSJkJY6oH82dbxgzTMOsa/panphlan_hpittmaniae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACypK68MIZWO0K7AR4BEcJQa/panphlan_janthropi16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAPyYug-7A99pp0uabK5xkWa/panphlan_jhoylei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABga1h6PKpp9Ph_YHKpt9UVa/panphlan_jignava16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD9HKXiTzjhZRpdpgT3Z-JFa/panphlan_kdenitrificans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAh8n6GFDFEQyBC65PyV5YQa/panphlan_kkingae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAClWJHfepWngC1glSJOL0TMa/panphlan_koralis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABRxwuL4tQm0hNaNNxNZ9D1a/panphlan_krhizophila16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAbFf4CLDcG8-tTiyF-_0gma/panphlan_lacidophilus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAeYXDGQ_LV36gYSQsxOUXOa/panphlan_lbuccalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADbkeHrUEYGBmLdRHHXz8YRa/panphlan_lcarnosum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA2wkS-nT4cvoEkpW49kpKVa/panphlan_lcoleohominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADJUtehRUUkqo9hNZEBvbOra/panphlan_lcrispatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACfiEZJG2gp5K9vngSVQlcFa/panphlan_lcurvatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADtmAkyFl78K2mRieht9BOCa/panphlan_ldelbrueckii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADGHJ0QuB362VsB6EEZqNBPa/panphlan_lfermentum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADCokbWYffm2QZmlKNjeHwFa/panphlan_lgasseri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADfnmHfPtigHkna1a9At95Na/panphlan_lgoodfellowii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAz1G97IgOSBtOxSAWiysHqa/panphlan_lhelveticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACNIpaDhJGgJOL4_gDEloKMa/panphlan_lhofstadii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADRh0jhY9aAGTK3oi5gdQDra/panphlan_liners16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAlY9khJ_vGpPh8j9qajtcEa/panphlan_ljensenii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADnd_qubQGAC5WgzXg4fiYca/panphlan_llactis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD9b1y1YP37ttmhGeFUfV7Oa/panphlan_lmesenteroides16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC5asEsVcrzQMps1gi5BSwEa/panphlan_lmirabilis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABAP__dYJmhG6WlKvPIx6oWa/panphlan_lplantarum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD4qQOy2gywpZbAGL0pA7jsa/panphlan_lreuteri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADEQe5zFRstQ5chPZuuR-KGa/panphlan_lrhamnosus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABt5b6SiflahJlH7_pcsqiZa/panphlan_lruminis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABV0y0uGRezDnxps6Y5DbTla/panphlan_lsaburreum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAlBCt9clJaQjCI1gERNl8sa/panphlan_lsakei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABwJ0A80xX6az8kM2dGcepJa/panphlan_lshahii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAI7Id_VSoVs2v7Ay3xYHcva/panphlan_lwadei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC8iJs3DOjHtsVR5FhcYnQ6a/panphlan_mabscessus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABCM12PRVNwhVNTWW8dDSRLa/panphlan_mcatarrhalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAD9w54yUmk-Iiw6MbkTUNqa/panphlan_mcoronavirus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACoXcfTf5G29yizzSHim6Gfa/panphlan_mcurtisii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABLk_xyyTlQrqBzORJV8O-Ta/panphlan_melsdenii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABG15vvjj4DYshd7DfEGI9ra/panphlan_mfuniformis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAypguqwKmUZw1U1jjP4twAa/panphlan_mhalotolerans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACxtbs4ZHl5XONjv9Hy_oHla/panphlan_mhominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABqlPEqiDYivo8WssPUTGA2a/panphlan_mhypermegale16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAsPVNtFUW8R_F-ld7rstmIa/panphlan_mluteus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACylfpm7HhCQ64nIoHMqW46a/panphlan_mmicronuciformis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB1_nSgf0gzCRxqe2y__ko6a/panphlan_mmulieris16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACcO0sUgFruB0xMIXiOnwFFa/panphlan_mmultacida16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAOENvZxUdt7HQznkLu_Y1-a/panphlan_morale16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACCg7oQVxJg-OhvnQX2WTh7a/panphlan_mrupellensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABEz8ejqD6Kgpdv0Jw8iE_Sa/panphlan_msmegmatis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADK-g113Bhn8dXgGsYu8hsma/panphlan_msmithii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAXAa2U2pIcbEy9nGLHyuska/panphlan_mtimonae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADGdKDCjvsWV6PjAHiyknWFa/panphlan_ncinerea16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA2Lwo1LpuriF2fXRWLbWV2a/panphlan_nelongata16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAANGB8X_kVnfmC6eGMoPIika/panphlan_nflavescens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABPx4zZZEkECEOIMDhFrYq4a/panphlan_ngonorrhoeae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACeaoMeCBiH8azRIA9RviJfa/panphlan_nlactamica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACi7vFBWNUvdfwW1FMczdm6a/panphlan_nmacacae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACSP_L1DiZymhzbdpheZuwIa/panphlan_nmeningitidis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACBy96bWcMKAlnEVOJjKWYha/panphlan_npolysaccharea16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAThvYnnUDSHi-Sqkj9jfs4a/panphlan_nsicca16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABc6EMTndPbhY4FQ-Xoe_vNa/panphlan_oformigenes16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAt_XN9dlVyYpzfpZxhLpd6a/panphlan_olaneus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABOh-r64wfCL3MONExCelSGa/panphlan_osinus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAhS0zKvJRfTOjXgZeKwRrHa/panphlan_osplanchnicus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAVdpQ6ozmJlUoxykqKhdQma/panphlan_pacidilactici16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACG2goXxjTV5KO98J8EgVFXa/panphlan_pacnes16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAk_y06MoAFRArMmFVCSzPEa/panphlan_pagglomerans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAALt382a-zBxYsDncsQTYCia/panphlan_palactolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADAdWRtb7W-XphU0kta4WQBa/panphlan_pamnii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADQDTTF1p1xmxXNFoP_moeFa/panphlan_panaerobius16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD5sFl0Lo5sHr9bttwXrZ6aa/panphlan_pananatis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACrfG8URfq6phJetoSNTA2_a/panphlan_pasaccharolytica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACCQUwq5iiQPHbPLQErOb_Da/panphlan_pavidum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAEItV9xSsydsey93URPz5Sa/panphlan_pbaroniae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACGwL_9atkKrHXvOk10eZb-a/panphlan_pbergensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADfkZuoXRDFNG2qlGAeLqsva/panphlan_pbivia16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD30SfPXJn4Zgl4ouk2ZMYla/panphlan_pbuccae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD25LMP3B-4DaFmWm7Su5qJa/panphlan_pbuccalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAFcCzj_-0wSJCLJ8pKGnHpa/panphlan_pcapillosus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABqBtD66ssxceu-3iRedIa7a/panphlan_pclara16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACNWUN4S0W9f2hQctqzJs7Ba/panphlan_pcopri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABAKPwmNUnlKYLPW4IRwg34a/panphlan_pdentalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADO4gz9HrszsQie6sSlnVrva/panphlan_pdenticola16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABd24sdRJp0fEzcc_eXn1lAa/panphlan_pdenticolens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAzlcbhFuJ2Bf1n3p3TlaSwa/panphlan_pdisiens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADdF8EDXhTfOMNtqXEwAAb_a/panphlan_pdistasonis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAIWpqgp50mb0YJuaj_pPcwa/panphlan_pelagibaca16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADv8DII_VNdd5fAMNlNEiPba/panphlan_pendodontalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD7o7ut799-A4MMvnmWakGJa/panphlan_pexcrementihominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADE7W6-hxWNkmKx50wHdkD1a/panphlan_pfreudenreichii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAeJEbhT4XFBsTseMwBMQqua/panphlan_pgingivalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACZT0kJ0zL7vsfCgtMkBac6a/panphlan_pgoldsteinii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAO_pJTqqUfRgPo9Pob-Z3ta/panphlan_pgranulosum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD6o68U0pdDU7yl9XD4SY-Ya/panphlan_pgulae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACi9bDtj7iUhSjsBIrFqjt1a/panphlan_pharei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAbYf3L48m05rJVwOrUHTnra/panphlan_phisticola16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABHGt-tuUPFj8dsRgP5Ybvla/panphlan_pintermedia16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAAlEU4e1cdlqBb53_qfEMha/panphlan_pjohnsonii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAy47vLd4hgImU_RU3sr1sJa/panphlan_placrimalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACiAdbkYVL-wBsRZ7Ad43tPa/panphlan_ploescheii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC42f8_Ki_mEGwLuBI795_Ta/panphlan_pmaculosa16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC7ABFSjRwhLDuSPg458gMLa/panphlan_pmarinusA15th80.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABNasaif3Y14mRNIquGdhJ8a/panphlan_pmarshii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACZmqWaxggglvFN-wSsHJaUa/panphlan_pmelaninogenica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACtThk5O2gPWJxbsuT3Fh8ea/panphlan_pmerdae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAELdG22Bn154lA5YUvX2ifa/panphlan_pmicans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAkx00mpqKfRPu_YIuA_cc-a/panphlan_pmicra16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADbQ5igqC4KvZ1s_0x_IF6wa/panphlan_pmirabilis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB-fZcpOCBLBzjtG0hUMaQNa/panphlan_pmultiformis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAeRp3Vk0-25WfUHBmwtKAva/panphlan_pnanceiensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACFgjakz0-MnLGD1c4xGh4Ka/panphlan_pnigrescens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAApwtK9tqtRn7Ot5gvF60AVa/panphlan_poralis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACnTGh-FbpE_W72l7x38KKJa/panphlan_poris16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABPhfY1yb74l59qHCgknPuLa/panphlan_poulorum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADYNbWySTv1f23QnVpcj__6a/panphlan_ppallens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABNdBhPPx6pvXbhBSzxq3Aoa/panphlan_ppiscolens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAZVUeLJlnHjXPEszLKV_iIa/panphlan_ppleuritidis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAkVzCsdZibdGTsSKogIDYua/panphlan_ppropionicum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADepD9Ig2MM1z0hOav6si-Ga/panphlan_psaccharolytica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC9eZObucsDUTGi1P4rdY_ra/panphlan_psalivae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAlTVVPZ0HH49D7l7BFR3Yza/panphlan_pstercorea16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACQouWcVm96UOqQ0oTXr2oxa/panphlan_pstomatis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABbnGfDXUIXuw475Kjyekgoa/panphlan_psuccinatutens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACjjgh8UtDlZMhLZUPQmwX5a/panphlan_pthermotolerans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD9QtE4g8hWBi4Wq1p5PZZNa/panphlan_ptimonensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADXqs56jQiA0Nprx-L-NRLLa/panphlan_pubiqueA15th80.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAgPbJDjB06m45FcYG8oVrwa/panphlan_puenonis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACniPjiPSJxtHaBTvCPtmfga/panphlan_pveroralis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAm-U95rExEsvrLzPYwD0zka/panphlan_pxylaniphila16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACCEqHd7FSPdXrHQVUMXVV6a/panphlan_raeria16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABQGelYDwDpe4vL8SkvsJRZa/panphlan_ralbus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABLmCaszqK9A4DOGTgJKluNa/panphlan_raquatilis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACswFaeiBHf7BEAIYRhcArfa/panphlan_rcallidus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAPzvkBexaW2ZZ3QbkFsYmSa/panphlan_rchampanellensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADRzglW4t2_iLtCtorEsfvua/panphlan_rdentocariosa16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABVSeCd9o6wwj0ENNlSftBca/panphlan_rflavefaciens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACGxr1ixf81VghKyzS_m-1La/panphlan_rgnavus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAyvhIqkfSCQ1wZA-zfJIFLa/panphlan_rhominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADUCzxZsY0odwyE9W3t5ZaOa/panphlan_rintestinalis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAKJZfOob5kE-_avjMcSvT2a/panphlan_rinulinivorans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB5lGwCQWaTdYSYf_qzrqH4a/panphlan_rmucilaginosa16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADMSZRjug_qKBashpPpgmBXa/panphlan_robeum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADXzKpIqcq6qwZKzyOFLoaTa/panphlan_roseovariusNubinhibens15.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABXtqhQmDuqP7CipXA5eZ3Ka/panphlan_roseovariusTM1035v15.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAABfIFpia98FsPuULs4GRS6a/panphlan_rpalustris16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD5Gh-3Bs4rlNiEctyMD036a/panphlan_rtorques16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAeA2jZn88oxDAR7y5ryBoja/panphlan_sanginosus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAArq1H98okRSaH3ZWr2RRmua/panphlan_sartemidis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACZVrnE1-NJd9sooKEd0Dvla/panphlan_saureus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAtU7tXuw1PdFPwleusBJWXa/panphlan_saustralis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA1HPx6MHmwnCFhTFh_11x4a/panphlan_sbongori16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADXMSJJtKCDk4C2H671E8S4a/panphlan_sconstellatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB1lwH6ohwo3LIxljBDU9bHa/panphlan_scristatus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACHtj-QtvwX2pj7B7CdcJjra/panphlan_sdysgalactiae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADNL7p-8COqEkJDtfInFGPha/panphlan_sechinoides16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD8hB_JI1y5VIa8QLWMAReza/panphlan_senterica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACmaAuEXmR0uKFWr3Ppcqjoa/panphlan_sepidermidis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAVDtFTUVaAm69bthcqVQFKa/panphlan_sexigua16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC7F3nfWm9VdMdTn-Lyoznla/panphlan_sflexneri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABiMR_LS4kXiwpBxgpRL5N9a/panphlan_sflueggei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAjLIEN-npgd0E7wVG59uj_a/panphlan_sgallolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADN6TYdGyrd2SHy1w3tploza/panphlan_sgordonii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADnhBRK4a2JOxD_e7SvFhCRa/panphlan_shaemolyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABLOAHqA41rjPbFt2MsGxb1a/panphlan_shominis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADELZxEah1aaZEDC5oItcWga/panphlan_sinfantarius16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA0c28ci19WNmLtC0uE1RX-a/panphlan_sinfantis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC8hRZ_V4UWBBb_0a-B_m1ka/panphlan_sinfelix16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB1GqzshSY9ZeoRYg6Buz_Wa/panphlan_sintermedius16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA4iasb95J9XwmCBP58hyLwa/panphlan_slongum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABuWRwbOZI1xz0Ui33ZeYm2a/panphlan_slugdunensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACj_jjYZRFDzfnWSeiEwwgwa/panphlan_smarcescens16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACrxrqUfzdHYv74G1JmrpMsa/panphlan_smoorei16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACkH0MsaIXuglVlBdkgyffra/panphlan_smutans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADD9onLJFuBI3NytIIB-XBIa/panphlan_snoxia16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABvIocTaTFQXEc0pJl6T_PVa/panphlan_soligofermentans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABM9vQb2vamrOEbCHVtw6pNa/panphlan_sparasanguinis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADQNvwDhNTQYsz53j6Qg3Iea/panphlan_spasteuri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADEG7Zy6lLGW_onXqyx0Sxza/panphlan_spasteurianus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC4LRHsj_pSoKfPUSKoVJ83a/panphlan_spiriformis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACb82DHHC7sKZ7i-ahhzyOPa/panphlan_spombe16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADB5H3sUTERUQaVnm9AFgQHa/panphlan_sproteamaculans16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADB5gJVkD7r6yhvakLtnjUZa/panphlan_spseudintermedius16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADavMtwXeVPxY6WXOqWoqYWa/panphlan_spseudopneumoniae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACwKIu20I0XkvPH0fNJ76SWa/panphlan_ssalivarius16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAw4uB3tOKdNspMo7LwhN5oa/panphlan_ssanguinis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA_QKfe_-EjOg_u_RUYsWrDa/panphlan_ssaprophyticus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACpY3801ztKoL1Y3D5Kf-2qa/panphlan_ssputigena16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADAO7qwZmhS6bONZtEHkHOva/panphlan_sthermophilus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAoa9S2Lsqj-WrKLtNnwxzra/panphlan_stigurinus16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC8z28ZyNPutIZxjwkXyKUCa/panphlan_sulfitobacter15.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD6M4BPWwrWigo6-IvRt62za/panphlan_svariabile16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAgrIFgDi1a5feiD8LokV1Ta/panphlan_svestibularis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAD2HDfKKvzoxmCz633e1zXUa/panphlan_swadsworthensis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACPFFgOCNXlJmEH-Nf3CeOOa/panphlan_swarneri16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADdet3MXTkSo_kmK7Ojw9Wqa/panphlan_swiggsiae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAAU9nJvX3dD0506Yzd5wrXqa/panphlan_syanoikuyae16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA-UL_3ZDEKcW-WqAcMim_ua/panphlan_tdenticola16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACHsQR2CAWewUNBVQEatcABa/panphlan_tforsythia16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAA8Oq1L619JARtLNyEG1ZVFa/panphlan_tmaltophilum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC-oJ04M4p9cnGdmciwzlo3a/panphlan_tmedium16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAC9cgOmvVTwl4-pAKcwJ3vfa/panphlan_totitidis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACZCV0Wtom-LdG04UhTWv_Ma/panphlan_tsanguinis16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADKDnkX4yY4r8TZDXQCKvmMa/panphlan_tsocranskii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACB8h8rkKjz6-TXmQfXpKfIa/panphlan_tvincentii16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABN8ui3NjBkm6KM40lNGYhaa/panphlan_uparvum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAB5XU6Y_cIgbf99TX9_s4Pga/panphlan_uurealyticum16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABKV60XnbbRhKBnxnQwTEHva/panphlan_vatypica16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AACiY_Qa5EEVYP04Fw22ZsNKa/panphlan_vcambriense16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AABiPKKzVGjwZKD273aeUCAna/panphlan_vdispar16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AADFcYFI87LiFnhC4Xo0EMFka/panphlan_vparvula16.zip
    wget https://www.dropbox.com/sh/rfwb4i9m8s40iba/AAByonypGq8ts3PF2gDjzmPEa/panphlan_vratti16.zip
